DEFAULT_DELAY_SEC = 4
MAX_DELAY_SEC = 120

APTOS_KEY_LENGTH = 66
EVM_ADDRESS_LENGTH = 42
MNEMONIC_LENGTH = 12
MODULE_NAME_MAX_LENGTH = 24
COLOR_LENGTH = 5

LOGGING_LEVEL = "INFO"

EXPLORER_BASE_URL = "https://explorer.aptoslabs.com/"

DEFAULT_WALLETS_THREADS_NUM = 4

VIRTUAL_TASK_PARAMETER = "is_virtual"