from colorama import Fore


class Color:
    BORDER = Fore.LIGHTBLUE_EX

    MODULE_NAME = Fore.LIGHTMAGENTA_EX
    MODULE_HEADER_TEXT = Fore.LIGHTCYAN_EX

    CONFIG_KEY_COLOR = Fore.LIGHTMAGENTA_EX
    CONFIG_VALUE_COLOR = Fore.LIGHTCYAN_EX
