donation_messages = [
    "Cheers for the caffeine boost!",
    "Your coffee donation made my day!",
    "Thanks for fueling my productivity!",
    "Thanks for the sip of happiness!",
    "Your donation is my cup of tea, thanks!",
    "You espresso'd your kindness, thank you!",
    "You've bean amazing, thanks for the coffee!",
    "Cheers for the coffee, you're a lifesaver!",
    "You're the cream to my coffee, thanks!",
    "Thanks for the coffee, you're a brew-tiful person!",
    "Grateful for the steamy support!",
    "Thanks for the coffee, you're a real mug!",
    "Your donation is the perfect blend, thanks!",
    "Thanks for the coffee, you've stirred my gratitude!",
    "Java-tastic donation, you rock!",
    "You've unleashed the caffeinated beast in me, thanks!",
    "You're the sugar, spice, and everything nice in my coffee!",
    "Thanks for the coffee, you're the espresso to my depresso!",
    "You've mocha'd my day, thank you!",
    "Thanks for the cosmic caffeine infusion!",
    "You're the wizard behind my magical brew, thanks!",
    "Thanks for the coffee, you're my caffeine superhero!",
    "You've just powered my coffee-fueled coding spree, thanks!",
    "Thanks for the coffee, you're the alchemist of my day!",
    "You've just caffeinated my soul, thank you!",
    "Thanks for the coffee, you're the unicorn in my fairy tale!",
    "You're the rocket fuel for my spaceship, thanks!",
    "Thanks for the coffee, you've activated my superpowers!",
    "You're the Dumbledore of coffee donations, thank you!",
    "Thanks for the coffee, you're the genie in my lamp!",
    "You've just brewed a potion of awesomeness, thanks!",
    "Thanks for the coffee, you're the Gandalf of my Middle-Earth!",
    "You're the Yoda of coffee wisdom, thank you!",
    "Coffee cheers, thanks!",
    "You made my day better!",
    "Thanks for the pick-me-up!",
    "You're awesome, thanks!",
    "Thanks, you're a gem!",
    "Coffee = happiness, thanks!",
    "Thanks for the energy!",
    "Thanks for the boost!",
    "You're a lifesaver!",
    "Thanks, you're the best!",
    "Thanks for the warmth!",
    "You brightened my day!",
    "Thanks for the smile!",
    "You're cool, thanks!",
    "Thanks for the joy!",
    "You're kind, thanks!",
    "Thanks for the lift!",
    "You're sweet, thanks!"
]
